services:
  next-app:
    image: node:18
    container_name: next-app
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # selenium-hub:
  #   image: selenium/hub:3.141.59
  #   container_name: selenium-hub
  #   ports:
  #     - "4444:4444"
  #   networks:
  #     - app-network

  # chrome:
  #   image: selenium/node-chrome:3.141.59
  #   container_name: chrome
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   networks:
  #     - app-network

  # firefox:
  #   image: selenium/node-firefox:3.141.59
  #   container_name: firefox
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
