name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto-merge Dependabot PRs
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash
          commitMessage: "Auto-merged by GitHub Actions"
