name: Label Dependabot PRs
permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-22.04

    steps:
      - name: Label Dependabot PRs
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
